Bug fixes

diff --git a/sh/overlay b/sh/overlay
--- a/sh/overlay
+++ b/sh/overlay
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -euo pipefail
 source $HOME/.venv/gpu/bin/activate
 
 shift_x=0
@@ -11,7 +12,7 @@ option_trunc=""
 
 # show usage and exit
 function show_usage () {
-    echo "$(basename "$0") [-x SHIFT_X] [-y SHIFT_Y] [-z SHIFT_Z] [-m REG_METHOD] [-f FILE_OVER] [-s FILE_SWEEP] [-t] FILE_BACK"
+    echo "$(basename "$0") [-x SHIFT_X] [-y SHIFT_Y] [-z SHIFT_Z] [-m REG_METHOD] [-f crop|fusion|(filename)] [-s FILE_SWEEP] [-t] FILE_BACK"
     exit 1
 }
 
@@ -38,6 +39,13 @@ if [[ "$file_over" == "" ]]; then
     if [[ "$file_over" == "" ]]; then
         file_over="$(find . -maxdepth 1 -iname '*EGFP*MMStack_Pos0_fusion_?.tif' | head -n 1)"
     fi
+elif [[ "$file_over.." == "fusion" ]]; then
+    file_over="$(find . -maxdepth 1 -iname '*EGFP*MMStack_Pos0_fusion_?.tif' | head -n 1)"
+elif [[ "$file_over.." == "crop" ]]; then
+    file_over="$(find . -maxdepth 1 -iname '*EGFP*MMStack_Pos0_crop_0.tif' | head -n 1)"
+else
+    echo "Invalid file name."
+    exit 1
 fi
 
 # find the overlay (sweeping) image if not specified
@@ -57,29 +65,44 @@ fi
 
 # process!
 if [[ "$file_back" =~ '.ome.tif' ]]; then
-    stem="$(echo ${file_back} | sed 's/\.ome\.tif$//')"
+    stem_back="$(echo ${file_back} | sed 's/\.ome\.tif$//')"
 elif [[ "$file_back" =~ '.tif' ]]; then
-    stem="$(echo ${file_back} | sed 's/\.tif$//')"
+    stem_back="$(echo ${file_back} | sed 's/\.tif$//')"
 else
     echo "Not an image file: ${file_back}"
     continue
 fi
 
-output_temp="${stem}_temp.tif"
-output_sweep="${stem}_sweep.tif"
-output_over="${stem}_${reg_method,,}_over.tif"
-output_final="${stem}_${reg_method,,}_over_final.tif"
-output_log="${stem}_log.txt"
+if [[ "$file_over" =~ '.ome.tif' ]]; then
+    stem_over="$(echo ${file_over} | sed 's/\.ome\.tif$//')"
+elif [[ "$file_over" =~ '.tif' ]]; then
+    stem_over="$(echo ${file_over} | sed 's/\.tif$//')"
+else
+    echo "Not an image file: ${file_over}"
+    continue
+fi
+
+
+output_temp="${stem_over}_temp.tif"
+output_sweep="${stem_back}_sweep.tif"
+output_over="${stem_back}_${reg_method,,}_over.tif"
+output_final="${stem_back}_${reg_method,,}_over_final.tif"
+output_log="${stem_back}_log.txt"
 
 echo "Overlay:" $(date) > $output_log
 echo "Dropping unused channels from the EGFP file" >> $output_log
 mmcrop.py -o "$output_temp" -c 0 "$file_over"
 
+echo "----------"
 echo "Overlaying crop_1 on crop_0, Shift X-Y-Z: $shift_x $shift_y $shift_z" >> $output_log
 mmoverlay.py -g 0 -o "$output_sweep" -c 0 0 -s "$shift_x" "$shift_y" "$shift_z" -e None "$file_sweep" "$file_back"
 
+echo "----------"
 echo "Overlaying EGFP on crop_0, method: ${reg_method,,}" >> $output_log
 mmoverlay.py -g 0 -o "$output_over" -c 0 0 -e "${reg_method^}" $option_trunc "$output_temp" "$output_sweep"
 
+echo "----------"
 echo "Dropping the channel used for registration" >> $output_log
 mmcrop.py -o "$output_final" -c -1 "$output_over"
+
+echo $file_over
